### ISSUE TITLE
Error in updating alert

### ISSUE THREAD

**Issue by Muhwu** [ruuvi/ruuvi-network-serverless#161]
2021-09-30T11:35:29.965Z	8297d55e-bdd6-44ab-91fe-5a9ae48a8b9e	ERROR	Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/task/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/task/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/task/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/task/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/task/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    --------------------
    at Protocol._enqueue (/var/task/node_modules/mysql/l

**Comment by ojousima** [comment]
Cannot find event like this In logs, will reopen if error pops up somehow
